import Head from 'next/head'
import Image from 'next/image'
export default function Home() {
  return (
    <div className='text-white'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hola</h1>
    </div>
  )
}
